//
//  PostShowWorkerTests.swift
//  Json Holder App
//
//  Created by Alejandro Fernández Ruiz on 28/11/2019.
//  Copyright (c) 2019 Alejandro Fernández Ruiz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Json_Holder_App
import XCTest

class PostShowWorkerTests: XCTestCase {
  // MARK: Subject under test
  
  var sut: PostShowWorker!
  
  // MARK: Test lifecycle
  
  override func setUp() {
    super.setUp()
    setupPostShowWorker()
  }
  
  override func tearDown() {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupPostShowWorker() {
    sut = PostShowWorker()
  }
  
  // MARK: Test doubles
  
  // MARK: Tests
  
  func testSomething() {
    // Given
    
    // When
    
    // Then
  }
}
