//
//  MainViewController.swift
//  Json Holder App
//
//  Created by Alejandro Fernández Ruiz on 24/11/2019.
//  Copyright (c) 2019 Alejandro Fernández Ruiz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainDisplayLogic: class {
    func setupView(viewModel: Main.Models.ViewModel)
    func showUsers()
    func showPostForUser()
    func showError(msg: String)
}

class MainViewController: BaseViewController {
    
    @IBOutlet weak var lblEmail: UILabel!
    @IBOutlet weak var lblPhone: UILabel!
    @IBOutlet weak var lblUserName: UILabel!
    @IBOutlet weak var lblName: UILabel!
    @IBOutlet weak var lblWebsite: UILabel!
    @IBOutlet weak var lblAddress: UILabel!
    
    @IBOutlet weak var stackView: UIStackView!
    @IBOutlet weak var collectionUsers: UICollectionView!
    @IBOutlet weak var collectionTodos: UICollectionView!
    @IBOutlet weak var collectionPosts: UICollectionView!
    
    
    var interactor: MainBusinessLogic?
    var router: (NSObjectProtocol & MainRoutingLogic & MainDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = MainInteractor()
        let presenter = MainPresenter()
        let router = MainRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        interactor?.getAllUsers()
    }
    
}

extension MainViewController: MainDisplayLogic {
    func showUsers() {
        collectionUsers.reloadData()
        collectionUsers.isHidden = false
    }
    
    func showPostForUser() {
        collectionPosts.reloadData()
        collectionTodos.reloadData()
        stackView.isHidden = false
    }
    
   
    
    func setupView(viewModel: Main.Models.ViewModel) {
        
        self.collectionUsers.isHidden = true
        self.stackView.isHidden = true
        self.lblName.text = ""
        self.lblEmail.text = ""
        self.lblPhone.text = ""
        self.lblAddress.text = ""
        self.lblWebsite.text = ""
        self.lblUserName.text = ""
        
        collectionUsers.register(UINib(nibName: String(describing: UserCollectionCell.self), bundle: nil), forCellWithReuseIdentifier: UserCollectionCell.cellIdentifier)
        collectionUsers.backgroundColor = UIColor.clear
        collectionUsers.delegate = self
        collectionUsers.dataSource = self
    }
    
    
    
    func showError(msg: String) {
        
    }
}

extension MainViewController: UICollectionViewDataSource, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout  {
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        if collectionView == collectionUsers {
            return self.interactor?.getUserCount() ?? 0
        } else if collectionView ==  collectionPosts {
            return self.interactor?.getPostCount() ?? 0
        } else if collectionView == collectionTodos {
            return self.interactor?.getTodoCount() ?? 0
        }
        return 0
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        return UICollectionViewCell()
    }
    
    
    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        if collectionView == collectionUsers {
            self.interactor?.userSelected(userIndex: indexPath.row)
        }
    }
    
}
