//
//  MainPresenter.swift
//  Json Holder App
//
//  Created by Alejandro Fernández Ruiz on 24/11/2019.
//  Copyright (c) 2019 Alejandro Fernández Ruiz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic {
  func setupView(response: Main.Models.Response)
  func presentAllUser(response: Main.Models.Response)
    func presentPostAndTodosForUserId(response: Main.Models.Response)
  func showError(msg: String)
}

class MainPresenter: MainPresentationLogic {

  weak var viewController: MainDisplayLogic?
  
  // MARK: Setup and update view
  
  func setupView(response: Main.Models.Response) {
         let viewModel = Main.Models.ViewModel()
         viewController?.setupView(viewModel: viewModel)
  }
    
  func presentAllUser(response: Main.Models.Response) {
        let viewModel = Main.Models.ViewModel()
        viewController?.setupView(viewModel: viewModel)
 }
    
    
    func presentPostAndTodosForUserId(response: Main.Models.Response) {
          
    }
    
    //MARK: Show error
    
    func showError(msg: String) {
        
    }
    
   
}
