//
//  MainInteractor.swift
//  Json Holder App
//
//  Created by Alejandro Fernández Ruiz on 24/11/2019.
//  Copyright (c) 2019 Alejandro Fernández Ruiz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainBusinessLogic {
    func setupView()
    func getAllUsers()
    func userSelected(userIndex: Int)
    func getUserCount() -> Int
    func getTodoCount() -> Int
    func getPostCount() -> Int
    func getDataForUserCell(index: Int) -> Main.Models.UserCellData
    func getDataForPostCell(index: Int) -> Main.Models.PostCellData
    func getDataForTodoCell(index: Int) -> Main.Models.TodosCellData
    func postSelected(index: IndexPath)
}

protocol MainDataStore {
    var userList: [User]? { get set }
    var todoList: [Todo]? { get set }
    var postList: [Post]? { get set }
}

class MainInteractor: MainBusinessLogic, MainDataStore {
    
    
    
    var todoList: [Todo]?
    var postList: [Post]?
    var userList: [User]?
    
    var presenter: MainPresentationLogic?
    var worker: MainWorker?
    
    
    
    func setupView() {
        worker = MainWorker()
        let response: Main.Models.Response = Main.Models.Response()
        presenter?.setupView(response: response)
    }
    
    func getAllUsers()  {
        
        worker?.getAllUsers(completionHandler: {[weak self] (userList, errorString) in
            if errorString.isEmpty {
                self?.userList = userList
                self?.presenter?.presentAllUser()
            } else {
                self?.presenter?.showError(msg: errorString)
            }
        })
    }
    
    func userSelected(userIndex: Int) {
       
        if let user = userList?.getElement(userIndex) {
            worker?.getPostByUserAndTodos(userId: user.id ?? 0, completionHandler: { [weak self] (todoList, postList, errorString) in
                if errorString.isEmpty {
                    var response = Main.Models.Response()
                    response.userSelected = user
                    self?.todoList = todoList
                    self?.postList = postList
                    self?.presenter?.presentPostAndTodosForUserId(response: response)
                } else {
                    self?.presenter?.showError(msg: errorString)
                }
            })
        }
    }
    func postSelected(index: IndexPath) {
        guard let destinationPost = postList?.getElement(index.row)  else {return}
        var response: Main.Models.Response = Main.Models.Response()
        response.postSelected = destinationPost
        self.presenter?.prepareNavigationFor(response: response)
    }
    
    
    func getUserCount() -> Int {
        return userList?.count ?? 0
    }
    
    func getTodoList() -> Int {
        return todoList?.count ?? 0
    }
    
    func getPostList() -> Int {
        return postList?.count ?? 0
    }
    
    func getTodoCount() -> Int {
        return todoList?.count ?? 0
    }
    
    func getPostCount() -> Int {
        return postList?.count ?? 0
    }
    
    func getDataForUserCell(index: Int) -> Main.Models.UserCellData {
        let user =  userList?.getElement(index)
        var data = Main.Models.UserCellData()
        data.user = user
        return data
    }
    
    func getDataForPostCell(index: Int) -> Main.Models.PostCellData {
        let post =  postList?.getElement(index)
        var data = Main.Models.PostCellData()
        data.post = post
        return data
    }
    
    func getDataForTodoCell(index: Int) -> Main.Models.TodosCellData {
        let todo =  todoList?.getElement(index)
        var data = Main.Models.TodosCellData()
        data.todo = todo
        return data
    }
    
    
}
