//
//  MainPresenter.swift
//  Json Holder App
//
//  Created by Alejandro Fernández Ruiz on 24/11/2019.
//  Copyright (c) 2019 Alejandro Fernández Ruiz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic {
    func setupView(response: Main.Models.Response)
    func presentAllUser()
    func presentPostAndTodosForUserId(response: Main.Models.Response)
    func prepareNavigationFor(response: Main.Models.Response)
    func showError(msg: String)
}

class MainPresenter: MainPresentationLogic {
    
    weak var viewController: MainDisplayLogic?
    
    // MARK: Setup and update view
    
    func setupView(response: Main.Models.Response) {
        let viewModel = Main.Models.ViewModel()
        viewController?.setupView(viewModel: viewModel)
    }
    
    func presentAllUser() {
        viewController?.showUsers()
    }
    
    
    func presentPostAndTodosForUserId(response: Main.Models.Response) {
        var model: Main.Models.ViewModel = Main.Models.ViewModel()
        model.user = response.userSelected
        self.viewController?.showPostForUser(viewModel: model)
    }
    
    
    // MARK: - PREPARE NAVIGATIONS
    func prepareNavigationFor(response: Main.Models.Response) {
        var model: Main.Models.ViewModel = Main.Models.ViewModel()
        model.selectedPost = response.postSelected
        self.viewController?.navigateToPostComments(viewModel: model)
    }
    // MARK: - SHOW ERRORS
    func showError(msg: String) {
        self.viewController?.showError(msg: msg)
    }
}
