//
//  MainRouter.swift
//  Json Holder App
//
//  Created by Alejandro Fernández Ruiz on 24/11/2019.
//  Copyright (c) 2019 Alejandro Fernández Ruiz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainRoutingLogic {
    func navigateToPostComments( viewModel: Main.Models.ViewModel)
}

protocol MainDataPassing {
    var dataStore: MainDataStore? { get set }
}

class MainRouter: NSObject, MainRoutingLogic, MainDataPassing {
    
    
    weak var viewController: MainViewController?
    var dataStore: MainDataStore?
    
    // MARK: Routing
    
    
    func navigateToPostComments(viewModel: Main.Models.ViewModel) {
        let storyboard: UIStoryboard = UIStoryboard(name: "PostShowStoryboard", bundle: nil)
        if let modalViewController = storyboard.instantiateInitialViewController() as? PostShowViewController {
            modalViewController.modalPresentationStyle = .overCurrentContext
            modalViewController.modalTransitionStyle = .crossDissolve
            modalViewController.router?.dataStore?.postData = viewModel.selectedPost
  
            viewController?.present(modalViewController, animated: true, completion: nil)
 
        }
    }
}
