//
//  MainModels.swift
//  Json Holder App
//
//  Created by Alejandro Fernández Ruiz on 24/11/2019.
//  Copyright (c) 2019 Alejandro Fernández Ruiz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Main {
  // MARK: Use cases
  
  enum Models {
    struct Request {
        var userId: Int?
    }
    struct Response {
        var user: [User]?
        var posts: [Post]?
        var todos: [Post]?
    }
    struct ViewModel {
        var user: [User]?
        var posts: [Post]?
        var todos: [Post]?
    }
    struct PostsViewModel {
        var postForUser : [Post]?
        var allUsers:[User]?
        var todosForUser: [Todo]?
    }
  }
}
