//
//  PostShowPresenter.swift
//  Json Holder App
//
//  Created by Alejandro Fernández Ruiz on 26/11/2019.
//  Copyright (c) 2019 Alejandro Fernández Ruiz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PostShowPresentationLogic
{
  func setupView(response: PostShow.Models.Response)
}

class PostShowPresenter: PostShowPresentationLogic
{
    
    
  weak var viewController: PostShowDisplayLogic?
  
  // MARK: MANAGE PRESENTATION LAYER
    
    func setupView(response:  PostShow.Models.Response) {
      let viewModel = PostShow.Models.ViewModel()
      viewController?.setupView(viewModel: viewModel)
    }
//  func presentSomething(response: PostShow.Something.Response)
//  {
//    let viewModel = PostShow.Something.ViewModel()
//    viewController?.displaySomething(viewModel: viewModel)
//  }
}
