//
//  PostShowPresenter.swift
//  Json Holder App
//
//  Created by Alejandro Fernández Ruiz on 26/11/2019.
//  Copyright (c) 2019 Alejandro Fernández Ruiz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PostShowPresentationLogic
{
    func setupView(response: PostShow.Models.Response)
    func makeDismiss()
    func showError(msg: String)
    func reloadTable()
    func setupPost(response:  PostShow.Models.Response)
}

class PostShowPresenter: PostShowPresentationLogic
{
    
    
    
    
    
    weak var viewController: PostShowDisplayLogic?
    
    // MARK: MANAGE PRESENTATION LAYER
    
    func setupView(response:  PostShow.Models.Response) {
        let viewModel = PostShow.Models.ViewModel()
        viewController?.setupView(viewModel: viewModel)
    }
    
    func setupPost(response: PostShow.Models.Response) {
        var viewModel:PostShow.Models.ViewModel = PostShow.Models.ViewModel()
        viewModel.title = response.postSelected?.title
        self.viewController?.showPost(viewModel: viewModel)
    }
    
    func reloadTable() {
        self.viewController?.reloadTable()
    }
    
     // MARK: - PREPARE NAVIGATIONS
    func makeDismiss() {
        viewController?.doClose()
    }
    
     // MARK: - SHOW ERRORS
       func showError(msg: String) {
           self.viewController?.showError(msg: msg)
       }
}
