//
//  PostShowModels.swift
//  Json Holder App
//
//  Created by Alejandro Fernández Ruiz on 26/11/2019.
//  Copyright (c) 2019 Alejandro Fernández Ruiz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PostShow
{
  // MARK: Use cases
  
  enum Models
  {
     struct Request {
           var postSelectedId: Int?
       }
       struct Response {
           var comments: Comment?
           var postSelected: Post?
       }
       struct ViewModel {
        var title: String?
        var id: Int?

       }
      
       
       struct CommentCellData {
            var name, email, body: String?
       }
       
  }
}
